---
- hosts: all
  become: yes
  tasks:
    - name: Mettez à jour le cache apt et assurez-vous que Vim, Curl et Unzip sont installés
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']